name: CMake

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**.md'
    - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '**.md'
    - 'docs/**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        artifact: ["WOW"]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}/src

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} ${{github.workspace}}/src
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-wow
        path: bin/*/*
        retention-days: 1
  create_release:
    name: "Prelease"
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ubuntu-latest-wow
          macos-latest-wow
          windows-latest-wow
    
        
#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       # Execute tests defined by the CMake configuration.  
#       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#       run: ctest -C ${{env.BUILD_TYPE}}
      
